name: Periodic health check

on:
  push:
    branches: [main]

  schedule:
    - cron: '0 6 * * *'   

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check that the app is responding
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-dtbk.onrender.com/broken
          max-attempts: 3
          retry-delay: 10s
          retry-all: true
